# Generated by Django 4.2 on 2026-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sent_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
