# Generated by Django 4.2 on 2026-04-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0002_offerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('group', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('total_sent', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OfferHistory',
        ),
    ]
