# Generated by Django 4.2 on 2026-04-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0005_passwordresetotp_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
