# Generated by Django 4.2 on 2026-04-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0006_loginattempt_passwordresetotp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
