# Generated by Django 4.2 on 2026-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0007_membershiptransaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
