# Generated by Django 4.2 on 2026-04-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0008_alter_customer_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='due_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
