# Generated by Django 4.2 on 2026-04-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0009_customer_due_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('due', 'Due')], default='paid', max_length=20),
        ),
    ]
