# Generated by Django 4.2 on 2026-04-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0010_bill_due_amount_bill_paid_amount_bill_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='due_balance',
            new_name='due_amount',
        ),
    ]
