# Generated by Django 4.2 on 2026-04-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
