# Generated by Django 4.2 on 2026-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0013_billitem_extra_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='old_due_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
