# Generated by Django 4.2 on 2026-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0014_bill_old_due_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='previous_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
