# Generated by Django 4.2 on 2026-05-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_alter_pricerule_cs_discount_alter_pricerule_min_qty_and_more'),
        ('star_admin', '0015_bill_previous_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.category'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='extra_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.size'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.variant'),
        ),
    ]
