# Generated by Django 4.2 on 2026-05-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0016_billitem_category_billitem_extra_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='shop_renewal_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
