# Generated by Django 6.0.4 on 2026-05-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0017_setting_shop_renewal_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='max_redeem_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='points_per_rupee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
