# Generated by Django 6.0.4 on 2026-05-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0018_alter_setting_max_redeem_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
