# Generated by Django 6.0.4 on 2026-05-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0019_bill_gross_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='current_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
