# Generated by Django 6.0.4 on 2026-05-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0020_bill_current_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='extra_charge_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
