# Generated by Django 6.0.4 on 2026-05-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0021_bill_extra_charge_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
