# Generated by Django 6.0.4 on 2026-05-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0023_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
