# Generated by Django 6.0.4 on 2026-05-09 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0024_order_is_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_admin.order'),
        ),
    ]
