# Generated by Django 6.0.4 on 2026-05-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_remove_digitalprice_qty_digitalprice_max_qty_and_more'),
        ('star_admin', '0026_staffactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='billing_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('digital', 'Digital')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='digital_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalcategory'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='digital_gsm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalgsm'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='digital_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalproduct'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.category'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.variant'),
        ),
    ]
