# Generated by Django 6.0.4 on 2026-05-16 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_remove_digitalprice_qty_digitalprice_max_qty_and_more'),
        ('star_admin', '0027_orderitem_billing_type_orderitem_digital_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='digital_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalcategory'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='digital_gsm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalgsm'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='digital_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalproduct'),
        ),
    ]
