# Generated by Django 6.0.4 on 2026-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0028_billitem_digital_category_billitem_digital_gsm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='work_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
