# Generated by Django 6.0.4 on 2026-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0029_orderitem_customer_type_orderitem_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='side',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='side_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
