# Generated by Django 6.0.4 on 2026-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0030_orderitem_side_orderitem_side_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='job',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
