# Generated by Django 6.0.4 on 2026-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0031_billitem_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='job',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
