# Generated by Django 6.0.4 on 2026-05-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_remove_digitalprice_product_and_more'),
        ('star_admin', '0032_orderitem_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='digital_lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitallamination'),
        ),
    ]
