# Generated by Django 6.0.4 on 2026-05-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_remove_digitalprice_product_and_more'),
        ('star_admin', '0033_orderitem_digital_lamination'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='digital_lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitallamination'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='side',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='side_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
