# Generated by Django 6.0.4 on 2026-05-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0034_billitem_digital_lamination_billitem_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_quotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
