# Generated by Django 6.0.4 on 2026-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0035_order_is_quotation_order_quotation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_quotation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quotation_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('pending', 'Pending'), ('progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
