# Generated by Django 6.0.4 on 2026-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0036_remove_order_is_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('pending', 'Pending'), ('progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='quotation', max_length=20),
        ),
    ]
