# Generated by Django 6.0.4 on 2026-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0037_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='manual_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
