# Generated by Django 6.0.4 on 2026-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0038_billitem_manual_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
