# Generated by Django 6.0.4 on 2026-05-29 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0040_quotation_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('lamination', models.CharField(blank=True, max_length=100)),
                ('side', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='star_admin.quotation')),
            ],
        ),
    ]
