# Generated by Django 6.0.4 on 2026-05-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0041_quotationitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='phone',
            new_name='customer_phone',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='order_date',
            new_name='quotation_date',
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
