# Generated by Django 6.0.4 on 2026-05-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_remove_digitalprice_product_and_more'),
        ('star_admin', '0042_rename_phone_quotation_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='lamination',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='customer_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='digital_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalcategory'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='digital_gsm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalgsm'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='digital_lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitallamination'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='digital_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.digitalproduct'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='side_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='billing_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('digital', 'Digital')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.category'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='job',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='side',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.size'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.variant'),
        ),
    ]
