# Generated by Django 6.0.4 on 2026-06-27 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_deliverytype_digitalprice_delivery_type_and_more'),
        ('star_admin', '0044_orderitem_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.deliverytype'),
        ),
    ]
