# Generated by Django 6.0.4 on 2026-06-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0045_quotationitem_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='work_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
