# Generated by Django 6.0.4 on 2026-06-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0048_billpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillPayment',
        ),
    ]
