# Generated by Django 6.0.4 on 2026-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0049_delete_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='manual_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
