# Generated by Django 6.0.4 on 2026-09-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0050_quotationitem_manual_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], default='in', max_length=3)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('message_type', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField(blank=True)),
                ('wa_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='star_admin.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
