# Generated by Django 6.0.4 on 2026-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_admin', '0051_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_media/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
