# Generated by Django 4.2 on 2026-04-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricerule',
            unique_together={('category', 'size', 'min_qty', 'max_qty')},
        ),
    ]
