# Generated by Django 4.2 on 2026-04-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricerule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerule',
            name='max_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
