# Generated by Django 4.2 on 2026-04-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_pricerule_max_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerule',
            options={'ordering': ['category', 'size', 'min_qty']},
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('category', 'name')},
        ),
    ]
