# Generated by Django 4.2 on 2026-04-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_pricerule_options_alter_size_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerule',
            name='double_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
