# Generated by Django 4.2 on 2026-04-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_pricerule_double_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.category')),
                ('member_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.membertype')),
            ],
        ),
    ]
