# Generated by Django 4.2 on 2026-04-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_categorydiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydiscount',
            name='discount_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categorydiscount',
            unique_together={('category', 'member_type')},
        ),
    ]
