# Generated by Django 4.2 on 2026-04-29 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_categorydiscount_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerule',
            name='cs_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='shop_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='membertype',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='min_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pricing.size')),
            ],
            options={
                'unique_together': {('size', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pricerule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='pricerule',
            unique_together={('category', 'size', 'variant', 'min_qty', 'max_qty')},
        ),
    ]
