# Generated by Django 4.2 on 2026-04-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_pricerule_cs_discount_pricerule_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricerule',
            old_name='single_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='pricerule',
            name='double_price',
        ),
    ]
