# Generated by Django 4.2 on 2026-04-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_rename_single_price_pricerule_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='variant',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
