# Generated by Django 4.2 on 2026-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_alter_variant_options_variant_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerule',
            name='cs_discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='min_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='shop_discount',
            field=models.FloatField(),
        ),
    ]
