# Generated by Django 6.0.4 on 2026-05-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_alter_pricerule_cs_discount_alter_pricerule_min_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalGSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.digitalcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=20)),
                ('gsm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.digitalgsm')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('one_day_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shop_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.digitalproduct')),
            ],
        ),
    ]
