# Generated by Django 6.0.4 on 2026-05-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_digitalcategory_digitalgsm_digitalproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalprice',
            name='qty',
        ),
        migrations.AddField(
            model_name='digitalprice',
            name='max_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalprice',
            name='min_qty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
