# Generated by Django 6.0.4 on 2026-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_remove_digitalprice_qty_digitalprice_max_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='lamination',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
