# Generated by Django 6.0.4 on 2026-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_digitalproduct_lamination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproduct',
            name='lamination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='side',
            field=models.CharField(choices=[('single', 'Single Side'), ('double', 'Double Side')], max_length=20),
        ),
    ]
