# Generated by Django 6.0.4 on 2026-05-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_alter_digitalproduct_lamination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='lamination',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='side',
        ),
        migrations.AddField(
            model_name='digitalprice',
            name='side',
            field=models.CharField(blank=True, choices=[('single', 'Single Side'), ('double', 'Double Side')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='digitalgsm',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsms', to='pricing.digitalcategory'),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='gsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricing.digitalgsm'),
        ),
        migrations.CreateModel(
            name='DigitalLamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laminations', to='pricing.digitalproduct')),
            ],
        ),
        migrations.AddField(
            model_name='digitalprice',
            name='lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.digitallamination'),
        ),
    ]
