# Generated by Django 6.0.4 on 2026-06-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_remove_digitalprice_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='digitalprice',
            name='delivery_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.deliverytype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='digitalprice',
            unique_together={('lamination', 'side', 'delivery_type', 'min_qty', 'max_qty')},
        ),
        migrations.RemoveField(
            model_name='digitalprice',
            name='one_day_rate',
        ),
    ]
